---
# file: site.yml

#  to install and deploy medifor base ipa server
#  ansible-playbook --private-key=private-key.pem   --extra-var "project_name=all" --v site.yml


# This playbook deploys proxy mapping tool.

- name: deploy docker pdns to {{ project_name }}
  become: yes
  become_user: root

 

  #deploy to dnsserver hosts 
  hosts: dnsservers

  roles:

    - pdns

