  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    tags:
      - docker    

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
      update_cache: yes
    tags:
      - docker

  - name: apt-get update
    apt: update_cache=true
    tags:
      - docker
  - name: Install docker and dependencies
    apt:
      name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce', 'python3-pip']
      state: present
      update_cache: yes
    tags:
      - docker

  # sudo groupadd docker
  - name: Create "docker" group
    group:
      name: "{{ docker_group }}"
      state: present
    tags:
      - docker
 
# sudo usermod -aG docker ubuntu
  - name: Add remote "{{ ansible_user }}" user to "{{ docker_group }}" group
    user:
      name: "{{ ansible_user }}"
      group: "{{ docker_group }}"
      append: yes
    tags:
      - docker
 
# sudo apt-get install docker-compose
  - name: Install docker-compose
    apt:
      name: docker-compose
      state: present
      update_cache: yes
    tags:
      - docker      
  - name: pip install docker
    pip:
      name:  docker
  - name: pip install docker-compose
    pip:
      name: docker-compose
 